force-app/main/default/objects/Settings__c/Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Settings</label>
</CustomObject>

force-app/main/default/objects/Settings__c/fields/ThemeAdditColor1__c.field-meta.xml
<CustomField>
    <fullName>ThemeAdditColor1__c</fullName>
    <label>Theme Addit Color 1</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settings__c/fields/ThemeAdditColor2__c.field-meta.xml
<CustomField>
    <fullName>ThemeAdditColor2__c</fullName>
    <label>Theme Addit Color 2</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settings__c/fields/ThemeAdditColor3__c.field-meta.xml
<CustomField>
    <fullName>ThemeAdditColor3__c</fullName>
    <label>Theme Addit Color 3</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settings__c/fields/ThemeAdditColor4__c.field-meta.xml
<CustomField>
    <fullName>ThemeAdditColor4__c</fullName>
    <label>Theme Addit Color 4</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settings__c/fields/ThemeAdditColor5__c.field-meta.xml
<CustomField>
    <fullName>ThemeAdditColor5__c</fullName>
    <label>Theme Addit Color 5</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settings__c/fields/ThemeAdditColor6__c.field-meta.xml
<CustomField>
    <fullName>ThemeAdditColor6__c</fullName>
    <label>Theme Addit Color 6</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settings__c/fields/ThemeAdditColor7__c.field-meta.xml
<CustomField>
    <fullName>ThemeAdditColor7__c</fullName>
    <label>Theme Addit Color 7</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settings__c/fields/ThemeBlueColor__c.field-meta.xml
<CustomField>
    <fullName>ThemeBlueColor__c</fullName>
    <label>Theme Blue Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settings__c/fields/ThemeGradient__c.field-meta.xml
<CustomField>
    <fullName>ThemeGradient__c</fullName>
    <label>Theme Gradient</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settings__c/fields/ThemeGreyColor__c.field-meta.xml
<CustomField>
    <fullName>ThemeGreyColor__c</fullName>
    <label>Theme Grey Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settings__c/fields/ThemeLightColor__c.field-meta.xml
<CustomField>
    <fullName>ThemeLightColor__c</fullName>
    <label>Theme Light Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settings__c/fields/ThemeMainColor__c.field-meta.xml
<CustomField>
    <fullName>ThemeMainColor__c</fullName>
    <label>Theme Main Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settings__c/fields/ThemeOppositeColor__c.field-meta.xml
<CustomField>
    <fullName>ThemeOppositeColor__c</fullName>
    <label>Theme Opposite Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settings__c/fields/ThemeSecondColor__c.field-meta.xml
<CustomField>
    <fullName>ThemeSecondColor__c</fullName>
    <label>Theme Second Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SettingsGetResponse.cls
global class SettingsGetResponse {

    global String themeMainColor { get; private set; }
    global String themeSecondColor { get; private set; }
    global String themeBlueColor { get; private set; }
    global String themeGreyColor { get; private set; }
    global String themeLightColor { get; private set; }
    global String themeOppositeColor { get; private set; }
    global String themeGradient { get; private set; }
    global String themeAdditColor1 { get; private set; }
    global String themeAdditColor2 { get; private set; }
    global String themeAdditColor3 { get; private set; }
    global String themeAdditColor4 { get; private set; }
    global String themeAdditColor5 { get; private set; }
    global String themeAdditColor6 { get; private set; }
    global String themeAdditColor7 { get; private set; }

    global SettingsGetResponse(Settings__c settings) {
        this.themeMainColor = settings.ThemeMainColor__c;
        this.themeSecondColor = settings.ThemeSecondColor__c;
        this.themeBlueColor = settings.ThemeBlueColor__c;
        this.themeGreyColor = settings.ThemeGreyColor__c;
        this.themeLightColor = settings.ThemeLightColor__c;
        this.themeOppositeColor = settings.ThemeOppositeColor__c;
        this.themeGradient = settings.ThemeGradient__c;
        this.themeAdditColor1 = settings.ThemeAdditColor1__c;
        this.themeAdditColor2 = settings.ThemeAdditColor2__c;
        this.themeAdditColor3 = settings.ThemeAdditColor3__c;
        this.themeAdditColor4 = settings.ThemeAdditColor4__c;
        this.themeAdditColor5 = settings.ThemeAdditColor5__c;
        this.themeAdditColor6 = settings.ThemeAdditColor6__c;
        this.themeAdditColor7 = settings.ThemeAdditColor7__c;
    }
}